name: Control Push
on: push # A chaque fois qu’un “push” est effectué sur le dépôt, le workflow GitHub Actions se déclenchent automatiquement.
jobs: # jobs => début de la section ou on défini les différentes tâches du workflow. 
  qa: # qa => c'est l'id interne du job (on peut choisir le nom que l'on souhaite. Ici, qa c'est pour quality assurance)
    name: Check tests # name => c’est le nom lisible qui apparaîtra dans l’interface GitHub Actions.
    runs-on: ubuntu-24.04 # runs-on => indique sur quelle machine (runner) le job va s’exécuter (ici une machine Linux Ubuntu 24.04).
    steps:
      # Étape 1 : récupérer le code source depuis le dépôt GitHub
      - name: Checkout on master # Nom affiché pour l’étape
        uses: actions/checkout@v3 # Action officielle de GitHub pour cloner le dépôt dans la VM
      # Étape 2 : installer Python sur la machine virtuelle
      - name: Set up Python # Nom affiché pour l’étape
        uses: actions/setup-python@master #le mot clé "uses" fait appel à un workflow réutilisable déjà existant sur github. 
        with: # Paramètres transmis à l'action
          python-version: "3.x"
      # Étape 3 : installer les dépendances nécessaires (pytest et flake8)
      - name: Install pytest and flake8
        run: |
          pip install pytest
          pip install flake8
      - name: Debug – List files
        run: ls -R
      # Étape 4 : exécuter les tests avec pytest
      - name: Run tests
        run: |
          pytest
      # Étape 5 : vérifier le style du code avec flake8.
      - name: Run tests
        run: |
          cd ${{ github.workspace }}   
          pytest -v                 
      - name: Run flake8
        uses: py-actions/flake8@v2